version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install
      # - sed -i s/"return ENV_TYPES.*"/"return ENV_TYPES\.${DEPLOY_ENV};"/i ./src/constants/env.constants.ts
      # - cp .env.${DEPLOY_ENV} .env
      # - aws s3 cp s3://${CONFIG_BUCKET}/configs/${DEPLOY_ENV}/.env.${DEPLOY_ENV} .env
      # - aws s3 cp s3://${CONFIG_BUCKET}/configs/${DEPLOY_ENV}/pk-${DEPLOY_ENV}-cf.pem pk-${DEPLOY_ENV}-cf.pem
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - rm -rf node_modules
      - find . -name '.DS_Store' -type f -delete
artifacts:
  files:
    - '**/*'
