import api from './api'
import { URI } from '@constants/uri.constants'
import { GameHardware, GameTitle } from './game.service'
import { Feature } from './user.service'

export type TournamentSearchParams = {
  page: number
  keyword: string
}

export type TournamentSearchResponse = {
  data: Array<TournamentResponse>
  links: any
}

export type TournamentResponse = {
  attributes: any
}

export type Meta = {
  current_page: number
  per_page: number
  total_count: number
  total_pages: number
}

export type TournamentFollowersResponse = {
  data: Array<FollowersResponse>
}

export type FollowersResponse = {
  attributes: any
}

export type TournamentResultsResponse = {
  data: Array<ResultsResponse>
}

export type ResultsResponse = {
  attributes: any
}

export type TournamentStatus = 'ready' | 'recruiting' | 'recruitment_closed' | 'ready_to_start' | 'in_progress' | 'completed' | 'cancelled'
export type TournamentRule = 'single' | 'double' | 'battle_royale'
export type TournamentDetail = {
  id: string
  type: 'tournament_details'
  attributes: {
    title: string
    overview: string
    notes: string
    rule: TournamentRule
    max_participants: number
    status: TournamentStatus
    is_freezed: boolean
    start_date: string
    end_date: string
    chat_room_id: string
    acceptance_start_date: string
    acceptance_end_date: string
    participant_type: 0 | 1 | 2 | 3
    area_id: number
    area_name: string
    address: string
    has_prize: boolean
    prize_amount: string
    terms_of_participation: string
    organizer_name: string
    summary: null | string
    background_tpl: number
    has_third_place: boolean
    retain_history: boolean
    t_type: 't_public' | 't_private'
    owner: {
      data: {
        id: 'string'
        type: 'user_list'
        attributes: {
          user_code: string
          nickname: string
          nickname2: null | string
          avatar: null | string
          features: Feature[]
          game_titles: GameTitle['attributes'][]
        }
      }
    }
    game_title: {
      data: GameTitle
    }
    game_hardware: {
      data: GameHardware
    }
    co_organizers: {
      data: []
    }
    cover_image: null | string
    summary_image: null | string
    interested_count: number
    participant_count: number
    my_role: null | string
    my_info: []
    my_position: null | string
    hash_key: string
    is_entered?: boolean
  }
}

export type TournamentDetailResponse = {
  data: TournamentDetail
}

export type EntryStatusResponse = {
  is_entry: boolean
}
export type TournamentMatchParticipant = {
  id: number
  role: 'admin' | 'participant' | 'interested' | 'co_organizer'
  name: string
  pid: number
  nickname: string
  user_code: string
}
export type TournamentMatchItem = {
  id: number
  round_no: number
  match_no: number
  score_guest: null | number
  score_home: null | number
  winner: string
  bracket: string
  is_edited: boolean
  is_editable: boolean
  home_user: TournamentMatchParticipant | null
  home_avatar: null | string
  guest_user: TournamentMatchParticipant | null
  guest_avatar: null | string
}

export type TournamentMatchRound = TournamentMatchItem[]

export type TournamentMatchResponse = {
  matches: TournamentMatchRound[]
  third_place_match: TournamentMatchRound
}

export const tournamentSearch = async (params: TournamentSearchParams): Promise<TournamentSearchResponse> => {
  const { data } = await api.get<TournamentSearchResponse>(URI.TOURNAMENTS_SEARCH, {
    params,
  })
  return data
}

export const tournamentFollowers = async (): Promise<TournamentFollowersResponse> => {
  const { data } = await api.get<TournamentFollowersResponse>(URI.TOURNAMENT_FOLLOWERS)
  return data
}

export const tournamentResults = async (): Promise<TournamentResultsResponse> => {
  const { data } = await api.get<TournamentResultsResponse>(URI.TOURNAMENT_RESULTS)
  return data
}

export const getTournamentDetail = async (hash_key: string): Promise<TournamentDetailResponse> => {
  const { data } = await api.get<TournamentDetailResponse>(`/web/v2/tournaments/${hash_key}/details`)
  return data
}

export const joinTournament = async (hash_key: string): Promise<void> => {
  const { data } = await api.post<void>(`/web/v2/tournaments/${hash_key}/details`)
  return data
}

export const leaveTournament = async (hash_key: string): Promise<void> => {
  const { data } = await api.post<void>(`/web/v2/tournaments/${hash_key}/details`)
  return data
}

export const getEntryStatus = async (hash_key: string): Promise<EntryStatusResponse> => {
  const { data } = await api.post<EntryStatusResponse>(`/web/v2/tournaments/${hash_key}/details`)
  return data
}

export const getTournamentMatches = async (): Promise<TournamentMatchResponse> => {
  return Promise.resolve({
    matches: [
      [
        {
          id: 6056,
          round_no: 0,
          match_no: 0,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 406,
            role: 'participant',
            name: 'participant406',
            pid: 1802,
            nickname: 'umtestuser',
            user_code: 'umtestuser79',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6057,
          round_no: 0,
          match_no: 1,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 414,
            role: 'participant',
            name: 'participant414',
            pid: 1810,
            nickname: 'umtestuser',
            user_code: 'umtestuser87',
          },
          home_avatar: null,
          guest_user: {
            id: 354,
            role: 'participant',
            name: 'participant354',
            pid: 1750,
            nickname: 'umtestuser',
            user_code: 'umtestuser27',
          },
          guest_avatar: null,
        },
        {
          id: 6058,
          round_no: 0,
          match_no: 2,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 370,
            role: 'participant',
            name: 'participant370',
            pid: 1766,
            nickname: 'umtestuser',
            user_code: 'umtestuser43',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6059,
          round_no: 0,
          match_no: 3,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 407,
            role: 'participant',
            name: 'participant407',
            pid: 1803,
            nickname: 'umtestuser',
            user_code: 'umtestuser80',
          },
          home_avatar: null,
          guest_user: {
            id: 418,
            role: 'participant',
            name: 'participant418',
            pid: 1814,
            nickname: 'umtestuser',
            user_code: 'umtestuser91',
          },
          guest_avatar: null,
        },
        {
          id: 6060,
          round_no: 0,
          match_no: 4,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 409,
            role: 'participant',
            name: 'participant409',
            pid: 1805,
            nickname: 'umtestuser',
            user_code: 'umtestuser82',
          },
          home_avatar: null,
          guest_user: {
            id: 426,
            role: 'participant',
            name: 'participant426',
            pid: 1822,
            nickname: 'umtestuser',
            user_code: 'umtestuser99',
          },
          guest_avatar: null,
        },
        {
          id: 6061,
          round_no: 0,
          match_no: 5,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 415,
            role: 'participant',
            name: 'participant415',
            pid: 1811,
            nickname: 'umtestuser',
            user_code: 'umtestuser88',
          },
          home_avatar: null,
          guest_user: {
            id: 394,
            role: 'participant',
            name: 'participant394',
            pid: 1790,
            nickname: 'umtestuser',
            user_code: 'umtestuser67',
          },
          guest_avatar: null,
        },
        {
          id: 6062,
          round_no: 0,
          match_no: 6,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 391,
            role: 'participant',
            name: 'participant391',
            pid: 1787,
            nickname: 'umtestuser',
            user_code: 'umtestuser64',
          },
          home_avatar: null,
          guest_user: {
            id: 378,
            role: 'participant',
            name: 'participant378',
            pid: 1774,
            nickname: 'umtestuser',
            user_code: 'umtestuser51',
          },
          guest_avatar: null,
        },
        {
          id: 6063,
          round_no: 0,
          match_no: 7,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 355,
            role: 'participant',
            name: 'participant355',
            pid: 1751,
            nickname: 'umtestuser',
            user_code: 'umtestuser28',
          },
          home_avatar: null,
          guest_user: {
            id: 339,
            role: 'participant',
            name: 'participant339',
            pid: 1735,
            nickname: 'umtestuser',
            user_code: 'umtestuser12',
          },
          guest_avatar: null,
        },
        {
          id: 6064,
          round_no: 0,
          match_no: 8,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 419,
            role: 'participant',
            name: 'participant419',
            pid: 1815,
            nickname: 'umtestuser',
            user_code: 'umtestuser92',
          },
          home_avatar: null,
          guest_user: {
            id: 433,
            role: 'participant',
            name: 'participant433',
            pid: 1829,
            nickname: 'umtestuser',
            user_code: 'umtestuser106',
          },
          guest_avatar: null,
        },
        {
          id: 6065,
          round_no: 0,
          match_no: 9,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 344,
            role: 'participant',
            name: 'participant344',
            pid: 1740,
            nickname: 'umtestuser',
            user_code: 'umtestuser17',
          },
          home_avatar: null,
          guest_user: {
            id: 430,
            role: 'participant',
            name: 'participant430',
            pid: 1826,
            nickname: 'umtestuser',
            user_code: 'umtestuser103',
          },
          guest_avatar: null,
        },
        {
          id: 6066,
          round_no: 0,
          match_no: 10,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 374,
            role: 'participant',
            name: 'participant374',
            pid: 1770,
            nickname: 'umtestuser',
            user_code: 'umtestuser47',
          },
          home_avatar: null,
          guest_user: {
            id: 400,
            role: 'participant',
            name: 'participant400',
            pid: 1796,
            nickname: 'umtestuser',
            user_code: 'umtestuser73',
          },
          guest_avatar: null,
        },
        {
          id: 6067,
          round_no: 0,
          match_no: 11,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 417,
            role: 'participant',
            name: 'participant417',
            pid: 1813,
            nickname: 'umtestuser',
            user_code: 'umtestuser90',
          },
          home_avatar: null,
          guest_user: {
            id: 347,
            role: 'participant',
            name: 'participant347',
            pid: 1743,
            nickname: 'umtestuser',
            user_code: 'umtestuser20',
          },
          guest_avatar: null,
        },
        {
          id: 6068,
          round_no: 0,
          match_no: 12,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 343,
            role: 'participant',
            name: 'participant343',
            pid: 1739,
            nickname: 'umtestuser',
            user_code: 'umtestuser16',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6069,
          round_no: 0,
          match_no: 13,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 403,
            role: 'participant',
            name: 'participant403',
            pid: 1799,
            nickname: 'umtestuser',
            user_code: 'umtestuser76',
          },
          home_avatar: null,
          guest_user: {
            id: 365,
            role: 'participant',
            name: 'participant365',
            pid: 1761,
            nickname: 'umtestuser',
            user_code: 'umtestuser38',
          },
          guest_avatar: null,
        },
        {
          id: 6070,
          round_no: 0,
          match_no: 14,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 369,
            role: 'participant',
            name: 'participant369',
            pid: 1765,
            nickname: 'umtestuser',
            user_code: 'umtestuser42',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6071,
          round_no: 0,
          match_no: 15,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 346,
            role: 'participant',
            name: 'participant346',
            pid: 1742,
            nickname: 'umtestuser',
            user_code: 'umtestuser19',
          },
          home_avatar: null,
          guest_user: {
            id: 364,
            role: 'participant',
            name: 'participant364',
            pid: 1760,
            nickname: 'umtestuser',
            user_code: 'umtestuser37',
          },
          guest_avatar: null,
        },
        {
          id: 6072,
          round_no: 0,
          match_no: 16,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 431,
            role: 'participant',
            name: 'participant431',
            pid: 1827,
            nickname: 'umtestuser',
            user_code: 'umtestuser104',
          },
          home_avatar: null,
          guest_user: {
            id: 332,
            role: 'participant',
            name: 'participant332',
            pid: 1728,
            nickname: 'umtestuser',
            user_code: 'umtestuser5',
          },
          guest_avatar: null,
        },
        {
          id: 6073,
          round_no: 0,
          match_no: 17,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 435,
            role: 'participant',
            name: 'participant435',
            pid: 1831,
            nickname: 'umtestuser',
            user_code: 'umtestuser108',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6074,
          round_no: 0,
          match_no: 18,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 333,
            role: 'participant',
            name: 'participant333',
            pid: 1729,
            nickname: 'umtestuser',
            user_code: 'umtestuser6',
          },
          home_avatar: null,
          guest_user: {
            id: 389,
            role: 'participant',
            name: 'participant389',
            pid: 1785,
            nickname: 'umtestuser',
            user_code: 'umtestuser62',
          },
          guest_avatar: null,
        },
        {
          id: 6075,
          round_no: 0,
          match_no: 19,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 423,
            role: 'participant',
            name: 'participant423',
            pid: 1819,
            nickname: 'umtestuser',
            user_code: 'umtestuser96',
          },
          home_avatar: null,
          guest_user: {
            id: 404,
            role: 'participant',
            name: 'participant404',
            pid: 1800,
            nickname: 'umtestuser',
            user_code: 'umtestuser77',
          },
          guest_avatar: null,
        },
        {
          id: 6076,
          round_no: 0,
          match_no: 20,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 429,
            role: 'participant',
            name: 'participant429',
            pid: 1825,
            nickname: 'umtestuser',
            user_code: 'umtestuser102',
          },
          home_avatar: null,
          guest_user: {
            id: 353,
            role: 'participant',
            name: 'participant353',
            pid: 1749,
            nickname: 'umtestuser',
            user_code: 'umtestuser26',
          },
          guest_avatar: null,
        },
        {
          id: 6077,
          round_no: 0,
          match_no: 21,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 359,
            role: 'participant',
            name: 'participant359',
            pid: 1755,
            nickname: 'umtestuser',
            user_code: 'umtestuser32',
          },
          home_avatar: null,
          guest_user: {
            id: 330,
            role: 'participant',
            name: 'participant330',
            pid: 1726,
            nickname: 'umtestuser',
            user_code: 'umtestuser3',
          },
          guest_avatar: null,
        },
        {
          id: 6078,
          round_no: 0,
          match_no: 22,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 375,
            role: 'participant',
            name: 'participant375',
            pid: 1771,
            nickname: 'umtestuser',
            user_code: 'umtestuser48',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6079,
          round_no: 0,
          match_no: 23,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 363,
            role: 'participant',
            name: 'participant363',
            pid: 1759,
            nickname: 'umtestuser',
            user_code: 'umtestuser36',
          },
          home_avatar: null,
          guest_user: {
            id: 392,
            role: 'participant',
            name: 'participant392',
            pid: 1788,
            nickname: 'umtestuser',
            user_code: 'umtestuser65',
          },
          guest_avatar: null,
        },
        {
          id: 6080,
          round_no: 0,
          match_no: 24,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 367,
            role: 'participant',
            name: 'participant367',
            pid: 1763,
            nickname: 'umtestuser',
            user_code: 'umtestuser40',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6081,
          round_no: 0,
          match_no: 25,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 358,
            role: 'participant',
            name: 'participant358',
            pid: 1754,
            nickname: 'umtestuser',
            user_code: 'umtestuser31',
          },
          home_avatar: null,
          guest_user: {
            id: 422,
            role: 'participant',
            name: 'participant422',
            pid: 1818,
            nickname: 'umtestuser',
            user_code: 'umtestuser95',
          },
          guest_avatar: null,
        },
        {
          id: 6082,
          round_no: 0,
          match_no: 26,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 338,
            role: 'participant',
            name: 'participant338',
            pid: 1734,
            nickname: 'umtestuser',
            user_code: 'umtestuser11',
          },
          home_avatar: null,
          guest_user: {
            id: 384,
            role: 'participant',
            name: 'participant384',
            pid: 1780,
            nickname: 'umtestuser',
            user_code: 'umtestuser57',
          },
          guest_avatar: null,
        },
        {
          id: 6083,
          round_no: 0,
          match_no: 27,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 383,
            role: 'participant',
            name: 'participant383',
            pid: 1779,
            nickname: 'umtestuser',
            user_code: 'umtestuser56',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6084,
          round_no: 0,
          match_no: 28,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 416,
            role: 'participant',
            name: 'participant416',
            pid: 1812,
            nickname: 'umtestuser',
            user_code: 'umtestuser89',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6085,
          round_no: 0,
          match_no: 29,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 356,
            role: 'participant',
            name: 'participant356',
            pid: 1752,
            nickname: 'umtestuser',
            user_code: 'umtestuser29',
          },
          home_avatar: null,
          guest_user: {
            id: 432,
            role: 'participant',
            name: 'participant432',
            pid: 1828,
            nickname: 'umtestuser',
            user_code: 'umtestuser105',
          },
          guest_avatar: null,
        },
        {
          id: 6086,
          round_no: 0,
          match_no: 30,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 329,
            role: 'participant',
            name: 'participant329',
            pid: 1725,
            nickname: 'umtestuser',
            user_code: 'umtestuser2',
          },
          home_avatar: null,
          guest_user: {
            id: 328,
            role: 'participant',
            name: 'participant328',
            pid: 1724,
            nickname: 'umtestuser',
            user_code: 'umtestuser1',
          },
          guest_avatar: null,
        },
        {
          id: 6087,
          round_no: 0,
          match_no: 31,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 341,
            role: 'participant',
            name: 'participant341',
            pid: 1737,
            nickname: 'umtestuser',
            user_code: 'umtestuser14',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6088,
          round_no: 0,
          match_no: 32,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 395,
            role: 'participant',
            name: 'participant395',
            pid: 1791,
            nickname: 'umtestuser',
            user_code: 'umtestuser68',
          },
          home_avatar: null,
          guest_user: {
            id: 350,
            role: 'participant',
            name: 'participant350',
            pid: 1746,
            nickname: 'umtestuser',
            user_code: 'umtestuser23',
          },
          guest_avatar: null,
        },
        {
          id: 6089,
          round_no: 0,
          match_no: 33,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 377,
            role: 'participant',
            name: 'participant377',
            pid: 1773,
            nickname: 'umtestuser',
            user_code: 'umtestuser50',
          },
          home_avatar: null,
          guest_user: {
            id: 402,
            role: 'participant',
            name: 'participant402',
            pid: 1798,
            nickname: 'umtestuser',
            user_code: 'umtestuser75',
          },
          guest_avatar: null,
        },
        {
          id: 6090,
          round_no: 0,
          match_no: 34,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 335,
            role: 'participant',
            name: 'participant335',
            pid: 1731,
            nickname: 'umtestuser',
            user_code: 'umtestuser8',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6091,
          round_no: 0,
          match_no: 35,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 388,
            role: 'participant',
            name: 'participant388',
            pid: 1784,
            nickname: 'umtestuser',
            user_code: 'umtestuser61',
          },
          home_avatar: null,
          guest_user: {
            id: 340,
            role: 'participant',
            name: 'participant340',
            pid: 1736,
            nickname: 'umtestuser',
            user_code: 'umtestuser13',
          },
          guest_avatar: null,
        },
        {
          id: 6092,
          round_no: 0,
          match_no: 36,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 413,
            role: 'participant',
            name: 'participant413',
            pid: 1809,
            nickname: 'umtestuser',
            user_code: 'umtestuser86',
          },
          home_avatar: null,
          guest_user: {
            id: 420,
            role: 'participant',
            name: 'participant420',
            pid: 1816,
            nickname: 'umtestuser',
            user_code: 'umtestuser93',
          },
          guest_avatar: null,
        },
        {
          id: 6093,
          round_no: 0,
          match_no: 37,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 386,
            role: 'participant',
            name: 'participant386',
            pid: 1782,
            nickname: 'umtestuser',
            user_code: 'umtestuser59',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6094,
          round_no: 0,
          match_no: 38,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 366,
            role: 'participant',
            name: 'participant366',
            pid: 1762,
            nickname: 'umtestuser',
            user_code: 'umtestuser39',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6095,
          round_no: 0,
          match_no: 39,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 428,
            role: 'participant',
            name: 'participant428',
            pid: 1824,
            nickname: 'umtestuser',
            user_code: 'umtestuser101',
          },
          home_avatar: null,
          guest_user: {
            id: 385,
            role: 'participant',
            name: 'participant385',
            pid: 1781,
            nickname: 'umtestuser',
            user_code: 'umtestuser58',
          },
          guest_avatar: null,
        },
        {
          id: 6096,
          round_no: 0,
          match_no: 40,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 376,
            role: 'participant',
            name: 'participant376',
            pid: 1772,
            nickname: 'umtestuser',
            user_code: 'umtestuser49',
          },
          home_avatar: null,
          guest_user: {
            id: 398,
            role: 'participant',
            name: 'participant398',
            pid: 1794,
            nickname: 'umtestuser',
            user_code: 'umtestuser71',
          },
          guest_avatar: null,
        },
        {
          id: 6097,
          round_no: 0,
          match_no: 41,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 387,
            role: 'participant',
            name: 'participant387',
            pid: 1783,
            nickname: 'umtestuser',
            user_code: 'umtestuser60',
          },
          home_avatar: null,
          guest_user: {
            id: 427,
            role: 'participant',
            name: 'participant427',
            pid: 1823,
            nickname: 'umtestuser',
            user_code: 'umtestuser100',
          },
          guest_avatar: null,
        },
        {
          id: 6098,
          round_no: 0,
          match_no: 42,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 393,
            role: 'participant',
            name: 'participant393',
            pid: 1789,
            nickname: 'umtestuser',
            user_code: 'umtestuser66',
          },
          home_avatar: null,
          guest_user: {
            id: 336,
            role: 'participant',
            name: 'participant336',
            pid: 1732,
            nickname: 'umtestuser',
            user_code: 'umtestuser9',
          },
          guest_avatar: null,
        },
        {
          id: 6099,
          round_no: 0,
          match_no: 43,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 349,
            role: 'participant',
            name: 'participant349',
            pid: 1745,
            nickname: 'umtestuser',
            user_code: 'umtestuser22',
          },
          home_avatar: null,
          guest_user: {
            id: 342,
            role: 'participant',
            name: 'participant342',
            pid: 1738,
            nickname: 'umtestuser',
            user_code: 'umtestuser15',
          },
          guest_avatar: null,
        },
        {
          id: 6100,
          round_no: 0,
          match_no: 44,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 360,
            role: 'participant',
            name: 'participant360',
            pid: 1756,
            nickname: 'umtestuser',
            user_code: 'umtestuser33',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6101,
          round_no: 0,
          match_no: 45,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 379,
            role: 'participant',
            name: 'participant379',
            pid: 1775,
            nickname: 'umtestuser',
            user_code: 'umtestuser52',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6102,
          round_no: 0,
          match_no: 46,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 334,
            role: 'participant',
            name: 'participant334',
            pid: 1730,
            nickname: 'umtestuser',
            user_code: 'umtestuser7',
          },
          home_avatar: null,
          guest_user: {
            id: 357,
            role: 'participant',
            name: 'participant357',
            pid: 1753,
            nickname: 'umtestuser',
            user_code: 'umtestuser30',
          },
          guest_avatar: null,
        },
        {
          id: 6103,
          round_no: 0,
          match_no: 47,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 397,
            role: 'participant',
            name: 'participant397',
            pid: 1793,
            nickname: 'umtestuser',
            user_code: 'umtestuser70',
          },
          home_avatar: null,
          guest_user: {
            id: 331,
            role: 'participant',
            name: 'participant331',
            pid: 1727,
            nickname: 'umtestuser',
            user_code: 'umtestuser4',
          },
          guest_avatar: null,
        },
        {
          id: 6104,
          round_no: 0,
          match_no: 48,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 408,
            role: 'participant',
            name: 'participant408',
            pid: 1804,
            nickname: 'umtestuser',
            user_code: 'umtestuser81',
          },
          home_avatar: null,
          guest_user: {
            id: 412,
            role: 'participant',
            name: 'participant412',
            pid: 1808,
            nickname: 'umtestuser',
            user_code: 'umtestuser85',
          },
          guest_avatar: null,
        },
        {
          id: 6105,
          round_no: 0,
          match_no: 49,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 361,
            role: 'participant',
            name: 'participant361',
            pid: 1757,
            nickname: 'umtestuser',
            user_code: 'umtestuser34',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6106,
          round_no: 0,
          match_no: 50,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 348,
            role: 'participant',
            name: 'participant348',
            pid: 1744,
            nickname: 'umtestuser',
            user_code: 'umtestuser21',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6107,
          round_no: 0,
          match_no: 51,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 373,
            role: 'participant',
            name: 'participant373',
            pid: 1769,
            nickname: 'umtestuser',
            user_code: 'umtestuser46',
          },
          home_avatar: null,
          guest_user: {
            id: 380,
            role: 'participant',
            name: 'participant380',
            pid: 1776,
            nickname: 'umtestuser',
            user_code: 'umtestuser53',
          },
          guest_avatar: null,
        },
        {
          id: 6108,
          round_no: 0,
          match_no: 52,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 434,
            role: 'participant',
            name: 'participant434',
            pid: 1830,
            nickname: 'umtestuser',
            user_code: 'umtestuser107',
          },
          home_avatar: null,
          guest_user: {
            id: 362,
            role: 'participant',
            name: 'participant362',
            pid: 1758,
            nickname: 'umtestuser',
            user_code: 'umtestuser35',
          },
          guest_avatar: null,
        },
        {
          id: 6109,
          round_no: 0,
          match_no: 53,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 371,
            role: 'participant',
            name: 'participant371',
            pid: 1767,
            nickname: 'umtestuser',
            user_code: 'umtestuser44',
          },
          home_avatar: null,
          guest_user: {
            id: 421,
            role: 'participant',
            name: 'participant421',
            pid: 1817,
            nickname: 'umtestuser',
            user_code: 'umtestuser94',
          },
          guest_avatar: null,
        },
        {
          id: 6110,
          round_no: 0,
          match_no: 54,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 368,
            role: 'participant',
            name: 'participant368',
            pid: 1764,
            nickname: 'umtestuser',
            user_code: 'umtestuser41',
          },
          home_avatar: null,
          guest_user: {
            id: 337,
            role: 'participant',
            name: 'participant337',
            pid: 1733,
            nickname: 'umtestuser',
            user_code: 'umtestuser10',
          },
          guest_avatar: null,
        },
        {
          id: 6111,
          round_no: 0,
          match_no: 55,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 381,
            role: 'participant',
            name: 'participant381',
            pid: 1777,
            nickname: 'umtestuser',
            user_code: 'umtestuser54',
          },
          home_avatar: null,
          guest_user: {
            id: 345,
            role: 'participant',
            name: 'participant345',
            pid: 1741,
            nickname: 'umtestuser',
            user_code: 'umtestuser18',
          },
          guest_avatar: null,
        },
        {
          id: 6112,
          round_no: 0,
          match_no: 56,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 399,
            role: 'participant',
            name: 'participant399',
            pid: 1795,
            nickname: 'umtestuser',
            user_code: 'umtestuser72',
          },
          home_avatar: null,
          guest_user: {
            id: 396,
            role: 'participant',
            name: 'participant396',
            pid: 1792,
            nickname: 'umtestuser',
            user_code: 'umtestuser69',
          },
          guest_avatar: null,
        },
        {
          id: 6113,
          round_no: 0,
          match_no: 57,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 411,
            role: 'participant',
            name: 'participant411',
            pid: 1807,
            nickname: 'umtestuser',
            user_code: 'umtestuser84',
          },
          home_avatar: null,
          guest_user: {
            id: 410,
            role: 'participant',
            name: 'participant410',
            pid: 1806,
            nickname: 'umtestuser',
            user_code: 'umtestuser83',
          },
          guest_avatar: null,
        },
        {
          id: 6114,
          round_no: 0,
          match_no: 58,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 405,
            role: 'participant',
            name: 'participant405',
            pid: 1801,
            nickname: 'umtestuser',
            user_code: 'umtestuser78',
          },
          home_avatar: null,
          guest_user: {
            id: 351,
            role: 'participant',
            name: 'participant351',
            pid: 1747,
            nickname: 'umtestuser',
            user_code: 'umtestuser24',
          },
          guest_avatar: null,
        },
        {
          id: 6115,
          round_no: 0,
          match_no: 59,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 401,
            role: 'participant',
            name: 'participant401',
            pid: 1797,
            nickname: 'umtestuser',
            user_code: 'umtestuser74',
          },
          home_avatar: null,
          guest_user: {
            id: 382,
            role: 'participant',
            name: 'participant382',
            pid: 1778,
            nickname: 'umtestuser',
            user_code: 'umtestuser55',
          },
          guest_avatar: null,
        },
        {
          id: 6116,
          round_no: 0,
          match_no: 60,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 424,
            role: 'participant',
            name: 'participant424',
            pid: 1820,
            nickname: 'umtestuser',
            user_code: 'umtestuser97',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6117,
          round_no: 0,
          match_no: 61,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 425,
            role: 'participant',
            name: 'participant425',
            pid: 1821,
            nickname: 'umtestuser',
            user_code: 'umtestuser98',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6118,
          round_no: 0,
          match_no: 62,
          score_guest: null,
          score_home: 0,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 372,
            role: 'participant',
            name: 'participant372',
            pid: 1768,
            nickname: 'umtestuser',
            user_code: 'umtestuser45',
          },
          home_avatar: null,
          guest_user: null,
          guest_avatar: null,
        },
        {
          id: 6119,
          round_no: 0,
          match_no: 63,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 352,
            role: 'participant',
            name: 'participant352',
            pid: 1748,
            nickname: 'umtestuser',
            user_code: 'umtestuser25',
          },
          home_avatar: null,
          guest_user: {
            id: 390,
            role: 'participant',
            name: 'participant390',
            pid: 1786,
            nickname: 'umtestuser',
            user_code: 'umtestuser63',
          },
          guest_avatar: null,
        },
      ],
      [
        {
          id: 6120,
          round_no: 1,
          match_no: 0,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 406,
            role: 'participant',
            name: 'participant406',
            pid: 1802,
            nickname: 'umtestuser',
            user_code: 'umtestuser79',
          },
          home_avatar: null,
          guest_user: {
            id: 414,
            role: 'participant',
            name: 'participant414',
            pid: 1810,
            nickname: 'umtestuser',
            user_code: 'umtestuser87',
          },
          guest_avatar: null,
        },
        {
          id: 6121,
          round_no: 1,
          match_no: 1,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 370,
            role: 'participant',
            name: 'participant370',
            pid: 1766,
            nickname: 'umtestuser',
            user_code: 'umtestuser43',
          },
          home_avatar: null,
          guest_user: {
            id: 418,
            role: 'participant',
            name: 'participant418',
            pid: 1814,
            nickname: 'umtestuser',
            user_code: 'umtestuser91',
          },
          guest_avatar: null,
        },
        {
          id: 6122,
          round_no: 1,
          match_no: 2,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 426,
            role: 'participant',
            name: 'participant426',
            pid: 1822,
            nickname: 'umtestuser',
            user_code: 'umtestuser99',
          },
          home_avatar: null,
          guest_user: {
            id: 394,
            role: 'participant',
            name: 'participant394',
            pid: 1790,
            nickname: 'umtestuser',
            user_code: 'umtestuser67',
          },
          guest_avatar: null,
        },
        {
          id: 6123,
          round_no: 1,
          match_no: 3,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 378,
            role: 'participant',
            name: 'participant378',
            pid: 1774,
            nickname: 'umtestuser',
            user_code: 'umtestuser51',
          },
          home_avatar: null,
          guest_user: {
            id: 339,
            role: 'participant',
            name: 'participant339',
            pid: 1735,
            nickname: 'umtestuser',
            user_code: 'umtestuser12',
          },
          guest_avatar: null,
        },
        {
          id: 6124,
          round_no: 1,
          match_no: 4,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 433,
            role: 'participant',
            name: 'participant433',
            pid: 1829,
            nickname: 'umtestuser',
            user_code: 'umtestuser106',
          },
          home_avatar: null,
          guest_user: {
            id: 430,
            role: 'participant',
            name: 'participant430',
            pid: 1826,
            nickname: 'umtestuser',
            user_code: 'umtestuser103',
          },
          guest_avatar: null,
        },
        {
          id: 6125,
          round_no: 1,
          match_no: 5,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 400,
            role: 'participant',
            name: 'participant400',
            pid: 1796,
            nickname: 'umtestuser',
            user_code: 'umtestuser73',
          },
          home_avatar: null,
          guest_user: {
            id: 417,
            role: 'participant',
            name: 'participant417',
            pid: 1813,
            nickname: 'umtestuser',
            user_code: 'umtestuser90',
          },
          guest_avatar: null,
        },
        {
          id: 6126,
          round_no: 1,
          match_no: 6,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 343,
            role: 'participant',
            name: 'participant343',
            pid: 1739,
            nickname: 'umtestuser',
            user_code: 'umtestuser16',
          },
          home_avatar: null,
          guest_user: {
            id: 403,
            role: 'participant',
            name: 'participant403',
            pid: 1799,
            nickname: 'umtestuser',
            user_code: 'umtestuser76',
          },
          guest_avatar: null,
        },
        {
          id: 6127,
          round_no: 1,
          match_no: 7,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 369,
            role: 'participant',
            name: 'participant369',
            pid: 1765,
            nickname: 'umtestuser',
            user_code: 'umtestuser42',
          },
          home_avatar: null,
          guest_user: {
            id: 364,
            role: 'participant',
            name: 'participant364',
            pid: 1760,
            nickname: 'umtestuser',
            user_code: 'umtestuser37',
          },
          guest_avatar: null,
        },
        {
          id: 6128,
          round_no: 1,
          match_no: 8,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 431,
            role: 'participant',
            name: 'participant431',
            pid: 1827,
            nickname: 'umtestuser',
            user_code: 'umtestuser104',
          },
          home_avatar: null,
          guest_user: {
            id: 435,
            role: 'participant',
            name: 'participant435',
            pid: 1831,
            nickname: 'umtestuser',
            user_code: 'umtestuser108',
          },
          guest_avatar: null,
        },
        {
          id: 6129,
          round_no: 1,
          match_no: 9,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 333,
            role: 'participant',
            name: 'participant333',
            pid: 1729,
            nickname: 'umtestuser',
            user_code: 'umtestuser6',
          },
          home_avatar: null,
          guest_user: {
            id: 404,
            role: 'participant',
            name: 'participant404',
            pid: 1800,
            nickname: 'umtestuser',
            user_code: 'umtestuser77',
          },
          guest_avatar: null,
        },
        {
          id: 6130,
          round_no: 1,
          match_no: 10,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 353,
            role: 'participant',
            name: 'participant353',
            pid: 1749,
            nickname: 'umtestuser',
            user_code: 'umtestuser26',
          },
          home_avatar: null,
          guest_user: {
            id: 359,
            role: 'participant',
            name: 'participant359',
            pid: 1755,
            nickname: 'umtestuser',
            user_code: 'umtestuser32',
          },
          guest_avatar: null,
        },
        {
          id: 6131,
          round_no: 1,
          match_no: 11,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 375,
            role: 'participant',
            name: 'participant375',
            pid: 1771,
            nickname: 'umtestuser',
            user_code: 'umtestuser48',
          },
          home_avatar: null,
          guest_user: {
            id: 392,
            role: 'participant',
            name: 'participant392',
            pid: 1788,
            nickname: 'umtestuser',
            user_code: 'umtestuser65',
          },
          guest_avatar: null,
        },
        {
          id: 6132,
          round_no: 1,
          match_no: 12,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 367,
            role: 'participant',
            name: 'participant367',
            pid: 1763,
            nickname: 'umtestuser',
            user_code: 'umtestuser40',
          },
          home_avatar: null,
          guest_user: {
            id: 358,
            role: 'participant',
            name: 'participant358',
            pid: 1754,
            nickname: 'umtestuser',
            user_code: 'umtestuser31',
          },
          guest_avatar: null,
        },
        {
          id: 6133,
          round_no: 1,
          match_no: 13,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 338,
            role: 'participant',
            name: 'participant338',
            pid: 1734,
            nickname: 'umtestuser',
            user_code: 'umtestuser11',
          },
          home_avatar: null,
          guest_user: {
            id: 383,
            role: 'participant',
            name: 'participant383',
            pid: 1779,
            nickname: 'umtestuser',
            user_code: 'umtestuser56',
          },
          guest_avatar: null,
        },
        {
          id: 6134,
          round_no: 1,
          match_no: 14,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 416,
            role: 'participant',
            name: 'participant416',
            pid: 1812,
            nickname: 'umtestuser',
            user_code: 'umtestuser89',
          },
          home_avatar: null,
          guest_user: {
            id: 432,
            role: 'participant',
            name: 'participant432',
            pid: 1828,
            nickname: 'umtestuser',
            user_code: 'umtestuser105',
          },
          guest_avatar: null,
        },
        {
          id: 6135,
          round_no: 1,
          match_no: 15,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 329,
            role: 'participant',
            name: 'participant329',
            pid: 1725,
            nickname: 'umtestuser',
            user_code: 'umtestuser2',
          },
          home_avatar: null,
          guest_user: {
            id: 341,
            role: 'participant',
            name: 'participant341',
            pid: 1737,
            nickname: 'umtestuser',
            user_code: 'umtestuser14',
          },
          guest_avatar: null,
        },
        {
          id: 6136,
          round_no: 1,
          match_no: 16,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 350,
            role: 'participant',
            name: 'participant350',
            pid: 1746,
            nickname: 'umtestuser',
            user_code: 'umtestuser23',
          },
          home_avatar: null,
          guest_user: {
            id: 377,
            role: 'participant',
            name: 'participant377',
            pid: 1773,
            nickname: 'umtestuser',
            user_code: 'umtestuser50',
          },
          guest_avatar: null,
        },
        {
          id: 6137,
          round_no: 1,
          match_no: 17,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 335,
            role: 'participant',
            name: 'participant335',
            pid: 1731,
            nickname: 'umtestuser',
            user_code: 'umtestuser8',
          },
          home_avatar: null,
          guest_user: {
            id: 388,
            role: 'participant',
            name: 'participant388',
            pid: 1784,
            nickname: 'umtestuser',
            user_code: 'umtestuser61',
          },
          guest_avatar: null,
        },
        {
          id: 6138,
          round_no: 1,
          match_no: 18,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 420,
            role: 'participant',
            name: 'participant420',
            pid: 1816,
            nickname: 'umtestuser',
            user_code: 'umtestuser93',
          },
          home_avatar: null,
          guest_user: {
            id: 386,
            role: 'participant',
            name: 'participant386',
            pid: 1782,
            nickname: 'umtestuser',
            user_code: 'umtestuser59',
          },
          guest_avatar: null,
        },
        {
          id: 6139,
          round_no: 1,
          match_no: 19,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 366,
            role: 'participant',
            name: 'participant366',
            pid: 1762,
            nickname: 'umtestuser',
            user_code: 'umtestuser39',
          },
          home_avatar: null,
          guest_user: {
            id: 385,
            role: 'participant',
            name: 'participant385',
            pid: 1781,
            nickname: 'umtestuser',
            user_code: 'umtestuser58',
          },
          guest_avatar: null,
        },
        {
          id: 6140,
          round_no: 1,
          match_no: 20,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 376,
            role: 'participant',
            name: 'participant376',
            pid: 1772,
            nickname: 'umtestuser',
            user_code: 'umtestuser49',
          },
          home_avatar: null,
          guest_user: {
            id: 427,
            role: 'participant',
            name: 'participant427',
            pid: 1823,
            nickname: 'umtestuser',
            user_code: 'umtestuser100',
          },
          guest_avatar: null,
        },
        {
          id: 6141,
          round_no: 1,
          match_no: 21,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 336,
            role: 'participant',
            name: 'participant336',
            pid: 1732,
            nickname: 'umtestuser',
            user_code: 'umtestuser9',
          },
          home_avatar: null,
          guest_user: {
            id: 349,
            role: 'participant',
            name: 'participant349',
            pid: 1745,
            nickname: 'umtestuser',
            user_code: 'umtestuser22',
          },
          guest_avatar: null,
        },
        {
          id: 6142,
          round_no: 1,
          match_no: 22,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 360,
            role: 'participant',
            name: 'participant360',
            pid: 1756,
            nickname: 'umtestuser',
            user_code: 'umtestuser33',
          },
          home_avatar: null,
          guest_user: {
            id: 379,
            role: 'participant',
            name: 'participant379',
            pid: 1775,
            nickname: 'umtestuser',
            user_code: 'umtestuser52',
          },
          guest_avatar: null,
        },
        {
          id: 6143,
          round_no: 1,
          match_no: 23,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 357,
            role: 'participant',
            name: 'participant357',
            pid: 1753,
            nickname: 'umtestuser',
            user_code: 'umtestuser30',
          },
          home_avatar: null,
          guest_user: {
            id: 331,
            role: 'participant',
            name: 'participant331',
            pid: 1727,
            nickname: 'umtestuser',
            user_code: 'umtestuser4',
          },
          guest_avatar: null,
        },
        {
          id: 6144,
          round_no: 1,
          match_no: 24,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 408,
            role: 'participant',
            name: 'participant408',
            pid: 1804,
            nickname: 'umtestuser',
            user_code: 'umtestuser81',
          },
          home_avatar: null,
          guest_user: {
            id: 361,
            role: 'participant',
            name: 'participant361',
            pid: 1757,
            nickname: 'umtestuser',
            user_code: 'umtestuser34',
          },
          guest_avatar: null,
        },
        {
          id: 6145,
          round_no: 1,
          match_no: 25,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 348,
            role: 'participant',
            name: 'participant348',
            pid: 1744,
            nickname: 'umtestuser',
            user_code: 'umtestuser21',
          },
          home_avatar: null,
          guest_user: {
            id: 373,
            role: 'participant',
            name: 'participant373',
            pid: 1769,
            nickname: 'umtestuser',
            user_code: 'umtestuser46',
          },
          guest_avatar: null,
        },
        {
          id: 6146,
          round_no: 1,
          match_no: 26,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 362,
            role: 'participant',
            name: 'participant362',
            pid: 1758,
            nickname: 'umtestuser',
            user_code: 'umtestuser35',
          },
          home_avatar: null,
          guest_user: {
            id: 421,
            role: 'participant',
            name: 'participant421',
            pid: 1817,
            nickname: 'umtestuser',
            user_code: 'umtestuser94',
          },
          guest_avatar: null,
        },
        {
          id: 6147,
          round_no: 1,
          match_no: 27,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 337,
            role: 'participant',
            name: 'participant337',
            pid: 1733,
            nickname: 'umtestuser',
            user_code: 'umtestuser10',
          },
          home_avatar: null,
          guest_user: {
            id: 381,
            role: 'participant',
            name: 'participant381',
            pid: 1777,
            nickname: 'umtestuser',
            user_code: 'umtestuser54',
          },
          guest_avatar: null,
        },
        {
          id: 6148,
          round_no: 1,
          match_no: 28,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 396,
            role: 'participant',
            name: 'participant396',
            pid: 1792,
            nickname: 'umtestuser',
            user_code: 'umtestuser69',
          },
          home_avatar: null,
          guest_user: {
            id: 411,
            role: 'participant',
            name: 'participant411',
            pid: 1807,
            nickname: 'umtestuser',
            user_code: 'umtestuser84',
          },
          guest_avatar: null,
        },
        {
          id: 6149,
          round_no: 1,
          match_no: 29,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 351,
            role: 'participant',
            name: 'participant351',
            pid: 1747,
            nickname: 'umtestuser',
            user_code: 'umtestuser24',
          },
          home_avatar: null,
          guest_user: {
            id: 401,
            role: 'participant',
            name: 'participant401',
            pid: 1797,
            nickname: 'umtestuser',
            user_code: 'umtestuser74',
          },
          guest_avatar: null,
        },
        {
          id: 6150,
          round_no: 1,
          match_no: 30,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 424,
            role: 'participant',
            name: 'participant424',
            pid: 1820,
            nickname: 'umtestuser',
            user_code: 'umtestuser97',
          },
          home_avatar: null,
          guest_user: {
            id: 425,
            role: 'participant',
            name: 'participant425',
            pid: 1821,
            nickname: 'umtestuser',
            user_code: 'umtestuser98',
          },
          guest_avatar: null,
        },
        {
          id: 6151,
          round_no: 1,
          match_no: 31,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 372,
            role: 'participant',
            name: 'participant372',
            pid: 1768,
            nickname: 'umtestuser',
            user_code: 'umtestuser45',
          },
          home_avatar: null,
          guest_user: {
            id: 352,
            role: 'participant',
            name: 'participant352',
            pid: 1748,
            nickname: 'umtestuser',
            user_code: 'umtestuser25',
          },
          guest_avatar: null,
        },
      ],
      [
        {
          id: 6152,
          round_no: 2,
          match_no: 0,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 406,
            role: 'participant',
            name: 'participant406',
            pid: 1802,
            nickname: 'umtestuser',
            user_code: 'umtestuser79',
          },
          home_avatar: null,
          guest_user: {
            id: 370,
            role: 'participant',
            name: 'participant370',
            pid: 1766,
            nickname: 'umtestuser',
            user_code: 'umtestuser43',
          },
          guest_avatar: null,
        },
        {
          id: 6153,
          round_no: 2,
          match_no: 1,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 426,
            role: 'participant',
            name: 'participant426',
            pid: 1822,
            nickname: 'umtestuser',
            user_code: 'umtestuser99',
          },
          home_avatar: null,
          guest_user: {
            id: 339,
            role: 'participant',
            name: 'participant339',
            pid: 1735,
            nickname: 'umtestuser',
            user_code: 'umtestuser12',
          },
          guest_avatar: null,
        },
        {
          id: 6154,
          round_no: 2,
          match_no: 2,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 433,
            role: 'participant',
            name: 'participant433',
            pid: 1829,
            nickname: 'umtestuser',
            user_code: 'umtestuser106',
          },
          home_avatar: null,
          guest_user: {
            id: 417,
            role: 'participant',
            name: 'participant417',
            pid: 1813,
            nickname: 'umtestuser',
            user_code: 'umtestuser90',
          },
          guest_avatar: null,
        },
        {
          id: 6155,
          round_no: 2,
          match_no: 3,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 343,
            role: 'participant',
            name: 'participant343',
            pid: 1739,
            nickname: 'umtestuser',
            user_code: 'umtestuser16',
          },
          home_avatar: null,
          guest_user: {
            id: 369,
            role: 'participant',
            name: 'participant369',
            pid: 1765,
            nickname: 'umtestuser',
            user_code: 'umtestuser42',
          },
          guest_avatar: null,
        },
        {
          id: 6156,
          round_no: 2,
          match_no: 4,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 431,
            role: 'participant',
            name: 'participant431',
            pid: 1827,
            nickname: 'umtestuser',
            user_code: 'umtestuser104',
          },
          home_avatar: null,
          guest_user: {
            id: 404,
            role: 'participant',
            name: 'participant404',
            pid: 1800,
            nickname: 'umtestuser',
            user_code: 'umtestuser77',
          },
          guest_avatar: null,
        },
        {
          id: 6157,
          round_no: 2,
          match_no: 5,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 353,
            role: 'participant',
            name: 'participant353',
            pid: 1749,
            nickname: 'umtestuser',
            user_code: 'umtestuser26',
          },
          home_avatar: null,
          guest_user: {
            id: 392,
            role: 'participant',
            name: 'participant392',
            pid: 1788,
            nickname: 'umtestuser',
            user_code: 'umtestuser65',
          },
          guest_avatar: null,
        },
        {
          id: 6158,
          round_no: 2,
          match_no: 6,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 358,
            role: 'participant',
            name: 'participant358',
            pid: 1754,
            nickname: 'umtestuser',
            user_code: 'umtestuser31',
          },
          home_avatar: null,
          guest_user: {
            id: 338,
            role: 'participant',
            name: 'participant338',
            pid: 1734,
            nickname: 'umtestuser',
            user_code: 'umtestuser11',
          },
          guest_avatar: null,
        },
        {
          id: 6159,
          round_no: 2,
          match_no: 7,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 416,
            role: 'participant',
            name: 'participant416',
            pid: 1812,
            nickname: 'umtestuser',
            user_code: 'umtestuser89',
          },
          home_avatar: null,
          guest_user: {
            id: 329,
            role: 'participant',
            name: 'participant329',
            pid: 1725,
            nickname: 'umtestuser',
            user_code: 'umtestuser2',
          },
          guest_avatar: null,
        },
        {
          id: 6160,
          round_no: 2,
          match_no: 8,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 350,
            role: 'participant',
            name: 'participant350',
            pid: 1746,
            nickname: 'umtestuser',
            user_code: 'umtestuser23',
          },
          home_avatar: null,
          guest_user: {
            id: 335,
            role: 'participant',
            name: 'participant335',
            pid: 1731,
            nickname: 'umtestuser',
            user_code: 'umtestuser8',
          },
          guest_avatar: null,
        },
        {
          id: 6161,
          round_no: 2,
          match_no: 9,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 420,
            role: 'participant',
            name: 'participant420',
            pid: 1816,
            nickname: 'umtestuser',
            user_code: 'umtestuser93',
          },
          home_avatar: null,
          guest_user: {
            id: 366,
            role: 'participant',
            name: 'participant366',
            pid: 1762,
            nickname: 'umtestuser',
            user_code: 'umtestuser39',
          },
          guest_avatar: null,
        },
        {
          id: 6162,
          round_no: 2,
          match_no: 10,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 376,
            role: 'participant',
            name: 'participant376',
            pid: 1772,
            nickname: 'umtestuser',
            user_code: 'umtestuser49',
          },
          home_avatar: null,
          guest_user: {
            id: 336,
            role: 'participant',
            name: 'participant336',
            pid: 1732,
            nickname: 'umtestuser',
            user_code: 'umtestuser9',
          },
          guest_avatar: null,
        },
        {
          id: 6163,
          round_no: 2,
          match_no: 11,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 360,
            role: 'participant',
            name: 'participant360',
            pid: 1756,
            nickname: 'umtestuser',
            user_code: 'umtestuser33',
          },
          home_avatar: null,
          guest_user: {
            id: 357,
            role: 'participant',
            name: 'participant357',
            pid: 1753,
            nickname: 'umtestuser',
            user_code: 'umtestuser30',
          },
          guest_avatar: null,
        },
        {
          id: 6164,
          round_no: 2,
          match_no: 12,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 361,
            role: 'participant',
            name: 'participant361',
            pid: 1757,
            nickname: 'umtestuser',
            user_code: 'umtestuser34',
          },
          home_avatar: null,
          guest_user: {
            id: 348,
            role: 'participant',
            name: 'participant348',
            pid: 1744,
            nickname: 'umtestuser',
            user_code: 'umtestuser21',
          },
          guest_avatar: null,
        },
        {
          id: 6165,
          round_no: 2,
          match_no: 13,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 421,
            role: 'participant',
            name: 'participant421',
            pid: 1817,
            nickname: 'umtestuser',
            user_code: 'umtestuser94',
          },
          home_avatar: null,
          guest_user: {
            id: 337,
            role: 'participant',
            name: 'participant337',
            pid: 1733,
            nickname: 'umtestuser',
            user_code: 'umtestuser10',
          },
          guest_avatar: null,
        },
        {
          id: 6166,
          round_no: 2,
          match_no: 14,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 411,
            role: 'participant',
            name: 'participant411',
            pid: 1807,
            nickname: 'umtestuser',
            user_code: 'umtestuser84',
          },
          home_avatar: null,
          guest_user: {
            id: 351,
            role: 'participant',
            name: 'participant351',
            pid: 1747,
            nickname: 'umtestuser',
            user_code: 'umtestuser24',
          },
          guest_avatar: null,
        },
        {
          id: 6167,
          round_no: 2,
          match_no: 15,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 425,
            role: 'participant',
            name: 'participant425',
            pid: 1821,
            nickname: 'umtestuser',
            user_code: 'umtestuser98',
          },
          home_avatar: null,
          guest_user: {
            id: 372,
            role: 'participant',
            name: 'participant372',
            pid: 1768,
            nickname: 'umtestuser',
            user_code: 'umtestuser45',
          },
          guest_avatar: null,
        },
      ],
      [
        {
          id: 6168,
          round_no: 3,
          match_no: 0,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 370,
            role: 'participant',
            name: 'participant370',
            pid: 1766,
            nickname: 'umtestuser',
            user_code: 'umtestuser43',
          },
          home_avatar: null,
          guest_user: {
            id: 426,
            role: 'participant',
            name: 'participant426',
            pid: 1822,
            nickname: 'umtestuser',
            user_code: 'umtestuser99',
          },
          guest_avatar: null,
        },
        {
          id: 6169,
          round_no: 3,
          match_no: 1,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 417,
            role: 'participant',
            name: 'participant417',
            pid: 1813,
            nickname: 'umtestuser',
            user_code: 'umtestuser90',
          },
          home_avatar: null,
          guest_user: {
            id: 369,
            role: 'participant',
            name: 'participant369',
            pid: 1765,
            nickname: 'umtestuser',
            user_code: 'umtestuser42',
          },
          guest_avatar: null,
        },
        {
          id: 6170,
          round_no: 3,
          match_no: 2,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 404,
            role: 'participant',
            name: 'participant404',
            pid: 1800,
            nickname: 'umtestuser',
            user_code: 'umtestuser77',
          },
          home_avatar: null,
          guest_user: {
            id: 392,
            role: 'participant',
            name: 'participant392',
            pid: 1788,
            nickname: 'umtestuser',
            user_code: 'umtestuser65',
          },
          guest_avatar: null,
        },
        {
          id: 6171,
          round_no: 3,
          match_no: 3,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 358,
            role: 'participant',
            name: 'participant358',
            pid: 1754,
            nickname: 'umtestuser',
            user_code: 'umtestuser31',
          },
          home_avatar: null,
          guest_user: {
            id: 329,
            role: 'participant',
            name: 'participant329',
            pid: 1725,
            nickname: 'umtestuser',
            user_code: 'umtestuser2',
          },
          guest_avatar: null,
        },
        {
          id: 6172,
          round_no: 3,
          match_no: 4,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 335,
            role: 'participant',
            name: 'participant335',
            pid: 1731,
            nickname: 'umtestuser',
            user_code: 'umtestuser8',
          },
          home_avatar: null,
          guest_user: {
            id: 420,
            role: 'participant',
            name: 'participant420',
            pid: 1816,
            nickname: 'umtestuser',
            user_code: 'umtestuser93',
          },
          guest_avatar: null,
        },
        {
          id: 6173,
          round_no: 3,
          match_no: 5,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 376,
            role: 'participant',
            name: 'participant376',
            pid: 1772,
            nickname: 'umtestuser',
            user_code: 'umtestuser49',
          },
          home_avatar: null,
          guest_user: {
            id: 360,
            role: 'participant',
            name: 'participant360',
            pid: 1756,
            nickname: 'umtestuser',
            user_code: 'umtestuser33',
          },
          guest_avatar: null,
        },
        {
          id: 6174,
          round_no: 3,
          match_no: 6,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 348,
            role: 'participant',
            name: 'participant348',
            pid: 1744,
            nickname: 'umtestuser',
            user_code: 'umtestuser21',
          },
          home_avatar: null,
          guest_user: {
            id: 421,
            role: 'participant',
            name: 'participant421',
            pid: 1817,
            nickname: 'umtestuser',
            user_code: 'umtestuser94',
          },
          guest_avatar: null,
        },
        {
          id: 6175,
          round_no: 3,
          match_no: 7,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 411,
            role: 'participant',
            name: 'participant411',
            pid: 1807,
            nickname: 'umtestuser',
            user_code: 'umtestuser84',
          },
          home_avatar: null,
          guest_user: {
            id: 372,
            role: 'participant',
            name: 'participant372',
            pid: 1768,
            nickname: 'umtestuser',
            user_code: 'umtestuser45',
          },
          guest_avatar: null,
        },
      ],
      [
        {
          id: 6176,
          round_no: 4,
          match_no: 0,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 426,
            role: 'participant',
            name: 'participant426',
            pid: 1822,
            nickname: 'umtestuser',
            user_code: 'umtestuser99',
          },
          home_avatar: null,
          guest_user: {
            id: 369,
            role: 'participant',
            name: 'participant369',
            pid: 1765,
            nickname: 'umtestuser',
            user_code: 'umtestuser42',
          },
          guest_avatar: null,
        },
        {
          id: 6177,
          round_no: 4,
          match_no: 1,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 392,
            role: 'participant',
            name: 'participant392',
            pid: 1788,
            nickname: 'umtestuser',
            user_code: 'umtestuser65',
          },
          home_avatar: null,
          guest_user: {
            id: 329,
            role: 'participant',
            name: 'participant329',
            pid: 1725,
            nickname: 'umtestuser',
            user_code: 'umtestuser2',
          },
          guest_avatar: null,
        },
        {
          id: 6178,
          round_no: 4,
          match_no: 2,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 420,
            role: 'participant',
            name: 'participant420',
            pid: 1816,
            nickname: 'umtestuser',
            user_code: 'umtestuser93',
          },
          home_avatar: null,
          guest_user: {
            id: 360,
            role: 'participant',
            name: 'participant360',
            pid: 1756,
            nickname: 'umtestuser',
            user_code: 'umtestuser33',
          },
          guest_avatar: null,
        },
        {
          id: 6179,
          round_no: 4,
          match_no: 3,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 421,
            role: 'participant',
            name: 'participant421',
            pid: 1817,
            nickname: 'umtestuser',
            user_code: 'umtestuser94',
          },
          home_avatar: null,
          guest_user: {
            id: 411,
            role: 'participant',
            name: 'participant411',
            pid: 1807,
            nickname: 'umtestuser',
            user_code: 'umtestuser84',
          },
          guest_avatar: null,
        },
      ],
      [
        {
          id: 6180,
          round_no: 5,
          match_no: 0,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 426,
            role: 'participant',
            name: 'participant426',
            pid: 1822,
            nickname: 'umtestuser',
            user_code: 'umtestuser99',
          },
          home_avatar: null,
          guest_user: {
            id: 392,
            role: 'participant',
            name: 'participant392',
            pid: 1788,
            nickname: 'umtestuser',
            user_code: 'umtestuser65',
          },
          guest_avatar: null,
        },
        {
          id: 6181,
          round_no: 5,
          match_no: 1,
          score_guest: null,
          score_home: null,
          winner: 'home',
          bracket: 'winner',
          is_edited: true,
          is_editable: false,
          home_user: {
            id: 420,
            role: 'participant',
            name: 'participant420',
            pid: 1816,
            nickname: 'umtestuser',
            user_code: 'umtestuser93',
          },
          home_avatar: null,
          guest_user: {
            id: 411,
            role: 'participant',
            name: 'participant411',
            pid: 1807,
            nickname: 'umtestuser',
            user_code: 'umtestuser84',
          },
          guest_avatar: null,
        },
      ],
      [
        {
          id: 6182,
          round_no: 6,
          match_no: 0,
          score_guest: null,
          score_home: null,
          winner: 'guest',
          bracket: 'winner',
          is_edited: true,
          is_editable: true,
          home_user: {
            id: 392,
            role: 'participant',
            name: 'participant392',
            pid: 1788,
            nickname: 'umtestuser',
            user_code: 'umtestuser65',
          },
          home_avatar: null,
          guest_user: {
            id: 420,
            role: 'participant',
            name: 'participant420',
            pid: 1816,
            nickname: 'umtestuser',
            user_code: 'umtestuser93',
          },
          guest_avatar: null,
        },
      ],
    ],
    third_place_match: [
      {
        id: 6183,
        round_no: 6,
        match_no: 0,
        score_guest: null,
        score_home: null,
        winner: null,
        bracket: 'third_place',
        is_edited: false,
        is_editable: true,
        home_user: {
          id: 426,
          role: 'participant',
          name: 'participant426',
          pid: 1822,
          nickname: 'umtestuser',
          user_code: 'umtestuser99',
        },
        home_avatar: null,
        guest_user: {
          id: 411,
          role: 'participant',
          name: 'participant411',
          pid: 1807,
          nickname: 'umtestuser',
          user_code: 'umtestuser84',
        },
        guest_avatar: null,
      },
    ],
  })
}
