export enum COMMUNITY_ACTION_TYPE {
  GET_COMMUNITY_LIST = 'community/list',
  GET_COMMUNITY_LIST_BY_USER = 'community/list_by_user',
  GET_FOLLOWERS_TOPIC_LIST = 'community/topic_followers',
  CLEAR_COMMUNITY_LIST = 'community/clearList',
  CLEAR_COMMUNITY_LIST_BY_USER = 'community/clearListByUser',
  GET_COMMUNITY_DETAIL = 'community/detail',
  CREATE_COMMUNITY = 'community/create',
  UPDATE_COMMUNITY = 'community/update',
  GET_COMMUNITY_FEATURES = 'community/features',
  CREATE_TOPIC = 'topic/create',
  GET_TOPIC_DETAIL = 'community/topic/detail',
  DELETE_TOPIC = 'topic/delete',
  CLEAR_TOPIC_DETAIL = 'community/topic/clearDetail',
  GET_COMMUNITY_MEMBERS = 'community/members',
  RESET_COMMUNITY_MEMBERS = 'community/resetMembers',
}
