export { default as UpsertForm } from './UpsertForm'
export { default as DetailContainer } from './Detail'
export { default as WinnersContainer } from './Winners'
export { default as BattlesContainer } from './battle_royale/Battles'
export { default as BattlesEditContainer } from './battle_royale/BattlesEdit'
export { default as MatchesContainer } from './tournament/Matches'
export { default as MatchesEditContainer } from './tournament/MatchesEdit'
export { default as ArenaHomeContainer } from './Home'
