export const ESRoutes = {
  WELCOME: '/welcome',
  HOME: '/home',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_PROFILE: '/register/profile',
  REGISTER_BY_EMAIL: '/register/by-email',
  REGISTER_CONFIRM: '/register/confirm',
  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_RESET: '/forgot-password/reset',
  FORGOT_PASSWORD_CONFIRM: '/forgot-password/confirm',
  PROFILE: '/profile',
  TOURNAMENTS: '/tournaments',
  SETTINGS: '/settings',
}
