export const ESRoutes = {
  WELCOME: '/welcome',
  HOME: '/home',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_PROFILE: '/register/profile',
  REGISTER_BY_EMAIL: '/register/by-email',
  REGISTER_CONFIRM: '/register/confirm',
  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_RESET: '/forgot-password/reset',
  FORGOT_PASSWORD_CONFIRM: '/forgot-password/confirm',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  GAME_EDIT: '/profile/game',
  TOURNAMENTS: '/tournaments',
  SETTINGS: '/settings',
  USER_SETTINGS: '/user-settings',
  MESSAGE: '/message/',
  RECRUITMENT_RECOMMENDED: '/recruitment/recommended',
  RECRUITMENT_FOLLOWER: '/recruitment/follower',
  EVENT_RECOMMENDED: '/event/recommended',
  TOURNAMENT_FOLLOWER_ENTERING: '/tournament/follower/entering',
  TOURNAMENT_FOLLOWER_ENDED: '/tournament/follower/ended',
  TOPIC_FOLLOWER: '/topic/follower',
}
