export const WEBSOCKET_PREFIX = 'WEBSOCKET'

export default {
  WEBSOCKET_PREFIX,
}

export enum CHAT_MESSAGE_TYPE {
  TEXT_MESSAGE = 1,
}

export enum CHAT_ACTION_TYPE {
  //socket
  INIT_CONNECTION = 'INIT_CONNECTION',
  GET_MEMBERS = 'GET_MEMBERS',
  GET_MESSAGES = 'GET_MESSAGES',
  SEND_MESSAGE = 'SEND_MESSAGE',
  PLAY_PRESS = 'PLAY_PRESS',
  COUNT_CHANGED = 'COUNT_CHANGED',
  RESET_CONNECTION = 'RESET_CONNECTION',
}
