const DOMAIN = process.env.NEXT_PUBLIC_API

export const URI = {
  DOMAIN,
  LOGIN: '/v2/auth/login',
  REFRESH: '/v2/auth/refresh_token',
  LOGIN_SOCIAL: '/v2/signup/social',
  REGISTER: '/v2/signup/register',
  REGISTER_PROFILE: '/v2/users/settings/stepweb1',
  CONFIRM: '/v2/signup/confirm',
  FORGOT_PASSWORD: '/v2/passwords/forgot',
  FORGOT_CONFIRM: '/v2/passwords/confirm',
  RESET_PASSWORD: '/v2/passwords/reset',
  PROFILE_UPDATE: '/v2/users/settings/step1',
  FOLLOWERS: '/v2/followers',
  FOLLOWING: '/v2/following',
  NG_WORDS: '/v1/ng_words',
  GET_PREFECTURES: 'v2/areas',
  USER_SETTINGS: '/v2/users/settings',
  USER_FEATURES: '/v2/user_features',
  GAME_TITLES_ALL: '/v2/game_titles_all',
  GAME_GENRES: '/v1/game_genres',
  GAME_TITLES: '/v1/game_titles',
  USER_DETAIL_PROFILE: '/v2/users/profile',
  USERS_SEARCH: '/v2/users/search',
  FOLLOW: '/v1/followers/follow',
  UNFOLLOW: '/v1/followers/unfollow',
  COMMUNITY_LIST: '/v1/communities/list',
  TOURNAMENTS_SEARCH: '/v1/tournaments/search',
  RECOMMENDED_USERS: '/v1/recommended_users',
  TOURNAMENTS_HISTORY_SEARCH: '/v1/tournaments/history_search',
  TOURNAMENTS_MEMBERS: '/v2/tournaments/:id/participants',
  SUGGESTED_TEAM_MEMBERS: '/v2/tournaments/team_recommended',
  JOIN_TOURNAMENT: '/v2/tournaments/:id/join',
  LEAVE_TOURNAMENT: '/v2/tournaments/:id/leave',
  CHECK_ENTRY_STATUS: '/v2/tournaments/:id/check_entry_status',
  PROFILE_ACTIVITY_LOG: '/v2/activity_logs',
  TOURNAMENT_FOLLOWERS: '/v2/tournaments/???',
  TOURNAMENT_RESULTS: '/v2/tournaments/???',
  TOURNAMENT_DETAIL: '/v1/tournaments/details/',
  TOURNAMENTS_PARTICIPANTS: 'v1/tournaments/:id/participants',
  COMMUNITY_FOLLOWERS_TOPICS: '/v2/communities/???',
  NICKNAMES_2: '/v2/users/get_nicknames2',
  USER_RECOMMENDATIONS: '/v2/users/recommendations',
  RECRUITMENT_RECOMMENDATIONS: '/v2/recruitments/recommendations',
  GAME_UPDATE: '/v2/users/game_titles',
  NOTIFICATION_LIST: '/v2/notification/own',
  NOTIFICATION_BADGE: '/v2/notification/badge',
  LOGOUT: '/v2/auth/logout',
}
