export const ACTION_VIDEO_TOP = {
  GET_LIST_ALL: 'videoTop/all',
  GET_LIST_LIVE: 'videoTop/live',
  GET_LIST_SCHEDULE: 'videoTop/schedule',
  GET_LIST_ARCHIVE: 'videoTop/archive',
  GET_VIDEO_POPULAR: 'videoTop/popular',
  GET_BANNER: 'videoTop/banner',
  GET_LIST_FAVORITE: 'videoTop/favorite',
  SEARCH_VIDEO: 'videoTop/searchVideo',
  RESET_SEARCH_VIDEO: 'videoTop/resetSearchVideo',
  VIDEO_DETAIL: 'video/detail',
  RESET_VIDEO_DETAIL: 'video/resetVideoDetail',
  RESET_LIVE: 'streaming/resetLiveVideo',
  RESET_SCHEDULE: 'streaming/resetLiveSchedule',
  RESET_ARCHIVE: 'streaming/resetLiveArchive',
  CHANGE_STREAMING_SECOND: 'streaming/changeStreamingSecond',
  CHANGE_VIDEO_TIME: 'streaming/changeVideoTime',
  CHANGE_PLAYED_SECOND: 'streaming/changePlayedSecond',
  CHANGE_IS_VIEWING_STREAM: 'streaming/changeIsViewingStream',
  CHANGE_IS_END_LIVE: 'streaming/changeIsEndLive',
  CHANGE_SEEK_COUNT: 'streaming/changeSeekCount',
  RESET_VIDEO_DETAIL_ERROR: 'video/resetVideoDetailError',
  CHANGE_IS_PAUSING_LIVE: 'streaming/changeIsPausingLive',
  CHANGE_IS_STREAMING_END: 'streaming/changeIsStreamingEnd',
  RESET_STATE: 'streaming/resetState',
  RESET_CHAT_STATE: 'streaming/resetChatState',
  CHANGE_VIDEO_VIEW_MODE: 'streaming/changeVideoViewMode',
  // SET_ACTIVE_TAB: 'streaming/setActiveTab',
  // SET_ACTIVE_SUB_TAB: 'streaming/setActiveSubTab',
  CHANGE__HOVERED_VIDEO_STATUS: 'streaming/changeIsHoveredVideoStatus',
  VIDEO_REF: 'streaming/videoRef',
  VIDEO_GIFT_MASTER: 'video/giftMaster',
  GET_RANKINGS: 'video/getRankings',
  UPDATE_USE_GIFT_FLAG: 'video/updateUseGiftFlag',
  GET_REPORT_REASON: 'video/get_report_reason',
  SEND_REPORT_REASON: 'video/send_video_report',
  UPDATE_TIP_FUNCTION_VISIBLE_STATE: 'video/tip_function_visible',
  CHANG_IS_FULL_SCREEN: 'video/change_is_full_screen',
}
