export const ACTION_VIDEO_TOP = {
  GET_LIST_ALL: 'videoTop/all',
  GET_LIST_LIVE: 'videoTop/live',
  GET_LIST_SCHEDULE: 'videoTop/schedule',
  GET_LIST_ARCHIVE: 'videoTop/archive',
  GET_VIDEO_POPULAR: 'videoTop/popular',
  GET_BANNER: 'videoTop/banner',
  GET_LIST_FAVORITE: 'videoTop/favorite',
  SEARCH_VIDEO: 'videoTop/searchVideo',
  RESET_SEARCH_VIDEO: 'videoTop/resetSearchVideo',
  VIDEO_DETAIL: 'video/detail',
  RESET_LIVE: 'streaming/resetLiveVideo',
  RESET_SCHEDULE: 'streaming/resetLiveSchedule',
  RESET_ARCHIVE: 'streaming/resetLiveArchive',
  CHANGE_STREAMING_SECOND: 'streaming/changeStreamingSecond',
  CHANGE_VIDEO_TIME: 'streaming/changeVideoTime',
  CHANGE_PLAYED_SECOND: 'streaming/changePlayedSecond',
  CHANGE_IS_VIEWING_STREAM: 'streaming/changeIsViewingStream',
  CHANGE_IS_END_LIVE: 'streaming/changeIsEndLive',
  CHANGE_SEEK_COUNT: 'streaming/changeSeekCount',
}
