export enum USER_PROFILE_ACTION_TYPE {
  GET_USER_PROFILE = 'profile/getUserProfile',
  GET_MEMBER_PROFILE = 'profile/getMemberProfile',
  TOURNAMENT_HISTORY = 'profile/tournamentHistory',
  PROFILE_ACTIVITY_LOG = 'profile/activityLog',
  PROFILE_NICKNAMES = 'profile/nicknames2',
  PROFILE_EDIT = 'profile/edit',
  RECOMMENDATIONS = 'user/recommendations',
  PROFILE_UPDATE = 'profile/profileUpdate',
  PROFILE_IMAGE = 'profile/profileImage',
  GAME_EDIT = 'profile/gameEdit',
  FOLLOW = 'profile/follow',
  UNFOLLOW = 'profile/unfollow',
  RECOMMENDED_EVENT = 'user/recommended_event',
  UPDATE_HOME_SETTINGS = 'user/update_home_settings',
  CHANGE_PASSWORD = 'user/change_password',
  CHANGE_EMAIL_CHECK = 'user/change_email_check',
  CHANGE_EMAIL = 'user/change_email',
  CHANGE_EMAIL_CONFIRM = 'user/change_email_confirm',
}
