export enum USER_PROFILE_ACTION_TYPE {
  GET_USER_PROFILE = 'profile/getUserProfile',
  GET_MEMBER_PROFILE = 'profile/getMemberProfile',
  TOURNAMENT_HISTORY = 'profile/tournamentHistory',
  PROFILE_ACTIVITY_LOG = 'profile/activityLog',
  PROFILE_NICKNAMES = 'profile/nicknames2',
  PROFILE_EDIT = 'profile/edit',
  RECOMMENDATIONS = 'user/recommendations',
  PROFILE_UPDATE = 'profile/profileUpdate',
  PROFILE_IMAGE = 'profile/profileImage',
  GAME_EDIT = 'profile/gameEdit',
  RECOMMENDED_EVENT = 'user/recommended_event',
  UPDATE_HOME_SETTINGS = 'user/update_home_settings',
  CHANGE_PASSWORD = 'user/change_password',
  CHANGE_EMAIL_CHECK = 'user/change_email_check',
  CHANGE_EMAIL = 'user/change_email',
  CHANGE_EMAIL_CONFIRM = 'user/change_email_confirm',
  CLEAR_CHANGE_EMAIL_STEPS = 'user/clear_change_email_steps',
  CLEAR_HOME_SETTINGS = 'user/clear_home_settings',
  FOLLOW = 'profile/follow',
  UNFOLLOW = 'profile/unfollow',
  FOLLOWERS = 'followers/getFollowers',
  CLEAR_FOLLOWERS = 'followers/clearFollowers',
  FOLLOWING = 'followers/getFollowing',
  CLEAR_FOLLOWING = 'followers/clearFollowing',
  FOLLOWING_INCREASE = 'followers/increase',
  FOLLOWING_DECREASE = 'followers/decrease',
}
